In [23]:
# Shailesha - Simple linear regression and numpyarray
import numpy as np
from sklearn.linear_model import LinearRegression

In [24]:
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
y = np.array([5, 20, 14, 32, 22, 38])

In [25]:
print(x)

[[ 5]
 [15]
 [25]
 [35]
 [45]
 [55]]


In [26]:
print(y)

[ 5 20 14 32 22 38]


In [27]:
# inear model creation
model = LinearRegression()

In [28]:
model.fit(x, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [29]:
model = LinearRegression().fit(x, y)

In [30]:
r_sq = model.score(x, y)

In [31]:
print('coefficient of determination:', r_sq)

coefficient of determination: 0.715875613747954


In [32]:
print('intercept:', model.intercept_)

intercept: 5.633333333333329


In [33]:
print('slope:', model.coef_)

slope: [0.54]


In [34]:
new_model = LinearRegression().fit(x, y.reshape((-1, 1)))

In [35]:
print('intercept:', new_model.intercept_)

intercept: [5.63333333]


In [36]:
print('slope:', new_model.coef_)

slope: [[0.54]]


In [37]:
y_pred = model.predict(x)

In [38]:
print('predicted response:', y_pred, sep='\n')

predicted response:
[ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]


In [39]:
y_pred = model.intercept_ + model.coef_ * x

In [40]:
print('predicted response:', y_pred, sep='\n')

predicted response:
[[ 8.33333333]
 [13.73333333]
 [19.13333333]
 [24.53333333]
 [29.93333333]
 [35.33333333]]


In [41]:
x_new = np.arange(5).reshape((-1, 1))

In [42]:
print(x_new)

[[0]
 [1]
 [2]
 [3]
 [4]]


In [43]:
y_new = model.predict(x_new)

In [44]:
print(y_new)

[5.63333333 6.17333333 6.71333333 7.25333333 7.79333333]
