<a href="https://colab.research.google.com/github/ShaileshaPMaganahalli/CPME_258_Deep_Learning/blob/master/homework_0/Ungraded_LinearRegression_NumpyArray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Shailesha - Homework_0_Ungraded Numpy Array**

In [0]:
# Shailesha - Simple linear regression and numpyarray
import numpy as np
from sklearn.linear_model import LinearRegression

In [0]:
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
y = np.array([5, 20, 14, 32, 22, 38])

In [0]:
print(x)

[[ 5]
 [15]
 [25]
 [35]
 [45]
 [55]]


In [0]:
print(y)

[ 5 20 14 32 22 38]


In [0]:
# inear model creation
model = LinearRegression()

In [0]:
model.fit(x, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [0]:
model = LinearRegression().fit(x, y)

In [0]:
r_sq = model.score(x, y)

In [0]:
print('coefficient of determination:', r_sq)

coefficient of determination: 0.7158756137479542


In [0]:
print('intercept:', model.intercept_)

intercept: 5.633333333333329


In [0]:
print('slope:', model.coef_)

slope: [0.54]


In [0]:
new_model = LinearRegression().fit(x, y.reshape((-1, 1)))

In [0]:
print('intercept:', new_model.intercept_)

intercept: [5.63333333]


In [0]:
print('slope:', new_model.coef_)

slope: [[0.54]]


In [0]:
y_pred = model.predict(x)

In [0]:
print('predicted response:', y_pred, sep='\n')

predicted response:
[ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]


In [0]:
y_pred = model.intercept_ + model.coef_ * x

In [0]:
print('predicted response:', y_pred, sep='\n')

predicted response:
[[ 8.33333333]
 [13.73333333]
 [19.13333333]
 [24.53333333]
 [29.93333333]
 [35.33333333]]


In [0]:
x_new = np.arange(5).reshape((-1, 1))

In [0]:
print(x_new)

[[0]
 [1]
 [2]
 [3]
 [4]]


In [0]:
y_new = model.predict(x_new)

In [0]:
print(y_new)

[5.63333333 6.17333333 6.71333333 7.25333333 7.79333333]
